services:
  auth-service:
    build:
      context: .
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/users_db
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=password
      - SPRING_KAFKA_PRODUCER_BOOTSTRAP-SERVERS=kafka:9092
    ports:
      - 8080:8080
    networks:
      - krainet-test-task-net
    depends_on:
      - db
    restart: unless-stopped
  db:
    image: "postgres:17-alpine"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
    volumes:
      - ./postgres/db_data:/var/lib/postgresql/data
      - ./postgres/init-db.sql:/docker-entrypoint-initdb.d/init-db.sql
    ports:
      - 5433:5432
    networks:
      - krainet-test-task-net
volumes:
  db_data:
networks:
  krainet-test-task-net:
    external: true
    name: krainet-test-task-net